name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: First Hello World Assignment
      id: first-hello-world-assignment
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: First Hello World Assignment
        setup-command: ''
        command: make test
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        FIRST-HELLO-WORLD-ASSIGNMENT_RESULTS: "${{steps.first-hello-world-assignment.outputs.result}}"
      with:
        runners: first-hello-world-assignment
